### ISSUE TITLE
Portuguese

### ISSUE THREAD

**Issue by FelixLuciano** [FelixLuciano/mini-elementarium#3]
**What is the name / country of that language?**
Brazilian portuguese

**Based on the name and country of origin, what would be the abbreviation for that language?**
pt-BR

**Translate the following document, this is an application language template:**
```yaml
---
user_interface:
  home: Início
  close: Fechar
  back: Voltar
  search: Pesquisar

views:
  language_dialog:
    leave_your_contribution: Deixe sua contribuição
    about_contributing: Contribuindo com o aplicativo o torna melhor para todo o mundo.
    choose_language: Escolha o idioma
    not_accurate: Não acurado
    contribute: Contribuir

  about:
    description: Mini Elementarium é um aplicativo informativo sobre os elementos da tabela periódica com uma interface colorida intuitiva e multi linguística para diversos dispositivos.
    license: Licença
    consultant: Consultoria de {0}
    peoples:
      maxim_lyutov: Maxim Lyutov

  chemical_info:
    family: Família
    atomic_mass: Massa atômica
    electronic_config: Configuração eletrônica
    see_more_on: Veja mais em
    chemical_element: Elemento químico
    families:
      hydrogen: Hidrogênio / não-metais
      noble_gases: Gáses nobres
      halogens: Halogênios
      alkali_metals: Metais alcalinos
      alkaline_marth_metals: Metais alcalinos terrosos
      transition_metals: Metais de transição
      post_transition_metals: Metais de transição interna
      semi_metals: Semimetais / Metalóides
      non_metals: Não metais
      lanthanoids: Lantanídeos
      actinoids: Actinídeos

chemicals:
  - Hidrogênio
  - Hélio
  - Lítio
  - Berílio
  - Boro
  - Carbono
  - Nitrogênio
  - Oxigênio
  - Fluor
  - Neônio
  - Sódio
  - Magnésio
  - Alumínio
  - Silício
  - Fósforo
  - Enxofre
  - Cloro
  - Argônio
  - Potássio
  - Cálcio
  - Escândio
  - Titânio
  - Vanádio
  - Cromo
  - Manganês
  - Ferro
  - Cobalto
  - Níquel
  - Cobre
  - Zinco
  - Gálio
  - Germânio
  - Arsênio
  - Selênio
  - Bromo
  - Criptônio
  - Rubídio
  - Estrôncio
  - Ítrio
  - Zircônio
  - Nióbio
  - Molibdênio
  - Tecnécio
  - Rutênio
  - Ródio
  - Paládio
  - Prata
  - Cádmio
  - Índio
  - Estanho
  - Antimônio
  - Telúrio
  - Iodo
  - Xenônio
  - Césio
  - Bário
  - Lantânio
  - Cério
  - Praseodimio
  - Neodímio
  - Promécio
  - Samário
  - Európio
  - Gadolíneo
  - Térbio
  - Disprósio
  - Hólmio
  - Érbio
  - Túlio
  - Itérbio
  - Lutércio
  - Háfnio
  - Tantálio
  - Tungstênio
  - Rênio
  - Ósmio
  - Irídio
  - Platina
  - ouro
  - Mercúrio
  - Tálio
  - Chumbo
  - Bismuto
  - Polônio
  - Astato
  - Radônio
  - Frâncio
  - Radônio
  - Actíneo
  - Tório
  - Protactínio
  - Urânio
  - Netúnio
  - Plutônio
  - Amércio
  - Cúrio
  - berquélio
  - Califórnio
  - Einstênio
  - Fêrmio
  - mandelévio
  - Nobélio
  - Laurêncio
  - Rutherfórdio
  - Dúbnio
  - Seabórgio
  - Bóhrio
  - Hássio
  - Meitnério
  - Darmstádtio
  - Roentgênio
  - Copernício
  - Nihônio
  - Fleróvio
  - Moscóvio
  - Livermório
  - Tennesso
  - Oganessônio

```
