### ISSUE TITLE
Russian

### ISSUE THREAD

**Issue by FelixLuciano** [FelixLuciano/mini-elementarium#4]
**What is the name / country of that language?**
Russian

**Based on the name and country of origin, what would be the abbreviation for that language?**
ru-RU

**Translate the following document, this is an application language template:**
```yaml
---
user_interface:
  home: Hачало
  close: Закрыть
  back: вернуться
  search: Поиск

views:
  language_dialog:
    leave_your_contribution: Оставьте свой вклад
    about_contributing: Вклад в приложение делает его лучше для всех.
    choose_language: выберите язык
    not_accurate: Не точный
    contribute: Делать вклад

  about:
    description: Информационное приложение по элементам периодической таблицы с красочным интуитивно понятным и многоязычным интерфейсом для различных устройств.
    license: ЛИЦЕНЗИЯ
    consultant: Консультант {0}
    peoples:
      maxim_lyutov: Максим Лютов

  chemical_info:
    family: Семейство
    atomic_mass: Атомная масса
    electronic_config: Электронная конфигурация
    see_more_on: Смотрите больше на
    chemical_element: Химический элемент
    families:
      hydrogen: Водород / Неметалл
      noble_gases: Благородные газы
      halogens: Галоген
      alkali_metals: Щелочные металлы
      alkaline_marth_metals: Щелочноземельные металлы
      transition_metals: Переходные металлы
      post_transition_metals: Постпереходные металлы
      semi_metals: Полуметаллы / металлоиды
      non_metals: Неметаллы
      lanthanoids: Лантаноиды
      actinoids: Актиноиды

chemicals:
  - Водород
  - Гелий
  - Литий
  - Бериллий
  - Бор
  - Углерод
  - Азот
  - Кислород
  - Фтор
  - Неон
  - Натрий
  - Магний
  - Алюминий
  - Кремний
  - Фосфор
  - Сера
  - Хлор
  - Аргон
  - Калий
  - Кальций
  - Скандий
  - Титан
  - Ванадий
  - Хром
  - Марганец
  - Железо
  - Кобальт
  - Никель
  - Медь
  - Цинк
  - Галлий
  - Германий
  - Мышьяк
  - Селен
  - Бром
  - Криптон
  - Рубидий
  - Стронций
  - Иттрий
  - Цирконий
  - Ниобий
  - Молибден
  - Технеций
  - Рутений
  - Родий
  - Палладий
  - Серебро
  - Кадмий
  - Индий
  - Олово
  - Сурьма
  - Теллур
  - Иод
  - Ксенон
  - Цезий
  - Барий
  - Лантан
  - Церий
  - Празеодим
  - Неодим
  - Прометий
  - Самарий
  - Европий
  - Гадолиний
  - Тербий
  - Диспрозий
  - Гольмий
  - Эрбий
  - Тулий
  - Иттербий
  - Лютеций
  - Гафний
  - Тантал
  - Вольфрам
  - Рений
  - Осмий
  - Иридий
  - Платина
  - Золото
  - Ртуть
  - Таллий
  - Свинец
  - Висмут
  - Полоний
  - Астат
  - Радон
  - Франций
  - Радий
  - Актиний
  - Торий
  - Протактиний
  - Уран
  - Нептуний
  - Плутоний
  - Америций
  - Кюрий
  - Берклий
  - Калифорний
  - Эйнштейний
  - Фермий
  - Менделевий
  - Нобелий
  - Лоуренсий
  - Резерфордий
  - Дубний
  - Сиборгий
  - Борий
  - Хассий
  - Мейтнерий
  - Дармштадтий
  - Рентгений
  - Коперниций
  - Нихоний
  - Флеровий
  - Московий
  - Ливерморий
  - Теннессин
  - Оганесон

```
