### ISSUE TITLE
[Language request] Test

### ISSUE THREAD

**Issue by FelixLuciano** [FelixLuciano/mini-elementarium#6]
**What is the name / country of that language?**
e.g American English

**Based on the name and country of origin, what would be the abbreviation for that language?**
e.g en-US

**Translate the following document, this is an application language template:**
```yaml
---
user_interface:
  home: Home
  close: Close
  back: Back
  search: Search

views:
  language_dialog:
    leave_your_contribution: Leave your contribution
    about_contributing: Contributing to the application makes it better for everyone.
    choose_language: Choose language
    not_accurate: Not accurate
    contribute: Contribute

  about:
    description: Mini Elementarium is an informative application about the elements of the periodic table with a colorful intuitive and multi linguistic interface for various devices.
    license: License
    consultant: Consultant {0}
    peoples:
      maxim_lyutov: Maxim Lyutov

  chemical_info:
    family: Family
    atomic_mass: Atomic mass
    electronic_config: Electronic configuration
    see_more_on: See more on
    chemical_element: Chemical element
    families:
      hydrogen: Hydrogen / Non-metals
      noble_gases: Noble gas
      halogens: Halogens
      alkali_metals: Alkali metals
      alkaline_marth_metals: Alkaline-earth metals
      transition_metals: Transition metals
      post_transition_metals: Post-transition metals
      semi_metals: Semimetals / metalloids
      non_metals: Non-metals
      lanthanoids: Lanthanoids
      actinoids: Actinoids

chemicals:
  - Hydrogen
  - Helium
  - Lithium
  - Berylium
  - Boron
  - Carbon
  - Nitrogen
  - Oxygen
  - Fluorine
  - Neon
  - Sodium
  - Magnesium
  - Aluminium
  - Silicon
  - Phosphorus
  - Sulfur
  - Chlorine
  - Argon
  - Potassium
  - Calcium
  - Scandium
  - Titanium
  - Vanadium
  - Chromium
  - Manganese
  - Iron
  - Cobalt
  - Nickel
  - Copper
  - Zinc
  - Gallium
  - Germanium
  - Arsenic
  - Selenium
  - Bromine
  - Kripton
  - Rubidium
  - Strontium
  - Yttrium
  - Zirconoum
  - Niobium
  - Molybdenum
  - Technetium
  - Ruthenium
  - Rhodium
  - Palladium
  - Silver
  - Cadmium
  - Induim
  - Tin
  - Antimony
  - Tellurium
  - Iodine
  - Xenon
  - Cesium
  - Barium
  - Lanthanum
  - Cerium
  - Praseodymium
  - Neodymium
  - Promethium
  - Samarium
  - Europium
  - Gadolium
  - Terbium
  - Dysprosium
  - Holmium
  - Erbium
  - Thulium
  - Ytterbium
  - Lutertium
  - Hafnium
  - Tantalum
  - Tungsten
  - Rhenium
  - Osmium
  - Iridium
  - Platinum
  - Gold
  - Mercury
  - Thalium
  - Lead
  - Bismuth
  - Polonium
  - Astatine
  - Radon
  - Francium
  - Radium
  - Actinum
  - Thorium
  - Protactinum
  - Uranium
  - Neptunium
  - Plutonium
  - Americium
  - Curium
  - Berkelium
  - Californium
  - Einstenium
  - Fermium
  - Mendelevium
  - Nobelium
  - Lawrencium
  - Rutherfordium
  - Dobnium
  - Seaborgium
  - Bohrium
  - Hassium
  - Meitnerium
  - Darmstadium
  - Roentgenium
  - Copernicium
  - Nihonium
  - Flerovium
  - Moscovium
  - Livermorium
  - Tennessine
  - Oganesson

```
